
[device.my-benchtop-nmr]  # This is the valve identifier
type = "Spinsolve"
host = "127.0.0.1"  # IP address of the PC running Spinsolve, 127.0.0.1 for local machine. Only necessary parameter.
port = 13000
sample_name = "automated-experiment"
solvent = "chloroform-d"
