openapi: 3.0.2
info:
  title: Flowchem - devices
  description: Flowchem is a python library to control a variety of instruments commonly
    found in chemistry labs.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 0.1.0a3
paths:
  /phidget-pressure/pressure-sensor/read-pressure:
    get:
      tags:
      - phidget-pressure
      - phidget-pressure
      summary: Read the pressure
      description: "Read from sensor, result to be expressed in units (optional)."
      operationId: run_phidget-pressure_pressure-sensor_read-pressure_get
      parameters:
        - required: false
          schema:
            title: units
            type: string
            default: bar
          name: units
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
