[build-system]
# Setuptools 64 and pip 21.3 are needed for editable installs, but a modern version of setuptools never hurts
requires = ["setuptools>64", "wheel", "pip>=22"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
flowchem = ["py.typed"]

[project]
name = "flowchem"
version = "0.1.0-alpha2"
description = "Flowchem is a python library to control a variety of instruments commonly found in chemistry labs."
readme = "README.md"
requires-python = ">=3.10"
keywords = ["chemistry", "automation", "laboratory", "science"]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License"
]
authors = [
    { name = "Dario Cambié", email = "2422614+dcambie@users.noreply.github.com" },
    { name = "Jakob Wolf", email = "Jakob.Wolf@mpikg.mpg.de" },
    { name = "Wei-Hsin Hsu", email = "Wei-hsin.Hsu@mpikg.mpg.de" },
]
dependencies = [
    "aioserial>=1.3.0",
    "asyncua>=0.9.92",
    "fastapi>=0.65.2",
    "getmac>=0.8.2",
    "loguru>=0.5.0",
    "lxml>=4.6.4",
    "networkx>=2.6.3",
    "nmrglue >= 0.8",
    "ord-schema>=0.3.0",
    "packaging>=21.3",
    "pint>=0.16.1",
    "pydantic>=1.8.2",
    "pyserial>=3",
    "rich_click>=0.3.0",
    "tenacity",
    'tomli; python_version<"3.11"',
    "unsync>=1.0.0",
    "uvicorn>=0.13.4",
    "google-api-python-client",
    "rich",
    'importlib-metadata; python_version<"3.8"',
]

[project.urls]
Homepage = "https://github.com/cambiegroup/flowchem"
Repository = "https://github.com/cambiegroup/flowchem"

[project.optional-dependencies]
dev = [
    "mypy",
    "flake8",
    "black",
    "pylint",
    "tox",
    "pre-commit"
]
test = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov"
]
phidget = [
    "phidget22>=1.7.20211005",
]
plot = [
    "matplotlib>=3.5.0",
]
doc = [
    "myst-parser",
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-rtd-theme",
]

[project.scripts]
 flowchem = "flowchem.cli:main"

[tool.pytest.ini_options]
testpaths = "tests"
asyncio_mode = "auto"
addopts = "-m 'not HApump and not Spinsolve and not FlowIR and not KPump' --cov=flowchem --cov-fail-under=30"
markers = [
    "HApump: tests requiring a local HA Elite11 connected.",
    "Spinsolve: tests requiring a connection to Spinsolve.",
    "FlowIR: tests requiring a connection to a FlowIR.",
    "KPump: tests for Azura compact" ]

[tool.mypy]
ignore_missing_imports = true
python_version = "3.10"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py310,pep8,mypy,black
isolated_build = true
minversion = 3.10.4

[testenv]
description = Run the tests with pytest under {basepython}
deps = pytest
changedir = {envtmpdir}
commands = python -m pytest {posargs} {toxinidir}
extras = dev,test


[testenv:pep8]
commands = flake8 --count --select=E9,F63,F7,F82 --show-source --statistics

[testenv:mypy]
commands = mypy --install-types --non-interactive .
"""
