[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "flowchem"
authors = [{name = "Dario Cambie, Jakob Wolf", email = "dario.cambie@mpikg.mpg.de"}]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
