openapi: 3.0.2
info:
  title: Flowchem - devices
  description: Flowchem is a python library to control a variety of instruments commonly
    found in chemistry labs.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 0.1.0a3
paths:
  /manson-power/power-on:
    put:
      tags:
      - manson-power
      - manson-power
      summary: Power on
      description: "Turn on temperature control."
      operationId: run_manson-power_run_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /manson-power/power-off:
    put:
      tags:
      - manson-power
      - manson-power
      summary: Power off
      description: "Turn off temperature control."
      operationId: set_method_manson-power_method_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /manson-power/current/:
    put:
      tags:
      - manson-power
      - manson-power
      summary: Set Current
      description: "Set the target current to the given string in natural language."
      operationId: set_sample_name_manson-power_sample_name_put
      parameters:
      - required: true
        schema:
          title: current
          type: string
        name: current
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /manson-power/current:
    get:
      tags:
        - manson-power
        - manson-power
      summary: Get Current
      description: "Return current in Ampere."
      operationId: set_sample_name_manson-power_sample_name_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
  /manson-power/voltage/:
    put:
      tags:
      - manson-power
      - manson-power
      summary: Set Voltage
      description: "Set the target voltage to the given string in natural language."
      operationId: set_sample_name_manson-power_sample_name_put
      parameters:
      - required: true
        schema:
          title: voltage
          type: string
        name: voltage
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /manson-power/voltage:
    get:
      tags:
        - manson-power
        - manson-power
      summary: Get voltage
      description: "Return current in Volt."
      operationId: set_sample_name_manson-power_sample_name_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
