openapi: 3.1.0
info:
  title: 'Flowchem - '
  description: Flowchem is a library to control instruments and devices commonly found
    in chemistry labs via an interoperable web API.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0a3
paths:
  /my-runzen-valve/:
    get:
      tags:
      - my-runzen-valve
      summary: Get Device Info
      operationId: get_device_info_my_runzen_valve__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInfo'
  /my-runzen-valve/distribution-valve/:
    get:
      tags:
      - my-runzen-valve
      - my-runzen-valve
      summary: Get Component Info
      description: "Retrieve the component's metadata.\n\nThis endpoint provides information\
        \ about the component, such as its name and associated hardware device.\n\n\
        Returns:\n--------\nComponentInfo\n    Metadata about the component."
      operationId: get_component_info_my_runzen_valve_distribution_valve__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentInfo'
  /my-runzen-valve/distribution-valve/position:
    get:
      tags:
      - my-runzen-valve
      - my-runzen-valve
      summary: Get Position
      description: Get current valve position.
      operationId: get_position_my_runzen_valve_distribution_valve_position_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    anyOf:
                    - type: integer
                    - type: 'null'
                title: Response Get Position My Runzen Valve Distribution Valve Position
                  Get
    put:
      tags:
      - my-runzen-valve
      - my-runzen-valve
      summary: Set Position
      description: Move valve to position, which connects named ports
      operationId: set_position_my_runzen_valve_distribution_valve_position_put
      parameters:
      - name: connect
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Connect
      - name: disconnect
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Disconnect
      - name: ambiguous_switching
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: boolean
          default: false
          title: Ambiguous Switching
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: boolean
                title: Response Set Position My Runzen Valve Distribution Valve Position
                  Put
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /my-runzen-valve/distribution-valve/connections:
    get:
      tags:
      - my-runzen-valve
      - my-runzen-valve
      summary: Connections
      description: 'Get the list of all available positions for this valve.

        This mainly has informative purpose'
      operationId: connections_my_runzen_valve_distribution_valve_connections_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValveInfo'
  /my-runzen-valve/distribution-valve/monitor_position:
    get:
      tags:
      - my-runzen-valve
      - my-runzen-valve
      summary: Get Monitor Position
      description: Get current valve position.
      operationId: get_monitor_position_my_runzen_valve_distribution_valve_monitor_position_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Get Monitor Position My Runzen Valve Distribution
                  Valve Monitor Position Get
    put:
      tags:
      - my-runzen-valve
      - my-runzen-valve
      summary: Set Monitor Position
      description: Move valve to position.
      operationId: set_monitor_position_my_runzen_valve_distribution_valve_monitor_position_put
      parameters:
      - name: position
        in: query
        required: true
        schema:
          type: string
          title: Position
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: boolean
                title: Response Set Monitor Position My Runzen Valve Distribution
                  Valve Monitor Position Put
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ComponentInfo:
      properties:
        name:
          type: string
          title: Name
          default: ''
        parent_device:
          type: string
          title: Parent Device
          default: ''
        type:
          type: string
          title: Type
          default: ''
        corresponding_class:
          items:
            type: string
          type: array
          title: Corresponding Class
          default: []
        owl_subclass_of:
          items:
            type: string
          type: array
          title: Owl Subclass Of
          default:
          - http://purl.obolibrary.org/obo/OBI_0000968
      type: object
      title: ComponentInfo
      description: Metadata associated with flowchem components.
    DeviceInfo:
      properties:
        manufacturer:
          type: string
          title: Manufacturer
          default: ''
        model:
          type: string
          title: Model
          default: ''
        version:
          type: string
          title: Version
          default: ''
        serial_number:
          anyOf:
          - type: string
          - type: integer
          title: Serial Number
          default: unknown
        components:
          additionalProperties:
            type: string
            minLength: 1
            format: uri
          type: object
          title: Components
          default: {}
        backend:
          type: string
          title: Backend
          default: flowchem v. 1.0.0a3
        authors:
          items:
            type: string
            format: name-email
          type: array
          title: Authors
          default: []
        additional_info:
          additionalProperties: true
          type: object
          title: Additional Info
          default: {}
      type: object
      title: DeviceInfo
      description: Metadata associated with hardware devices.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValveInfo:
      properties:
        ports:
          items:
            items: {}
            type: array
          type: array
          title: Ports
        positions:
          additionalProperties:
            items:
              items:
                anyOf:
                - type: integer
                - type: 'null'
              type: array
            type: array
          type: object
          title: Positions
      type: object
      required:
      - ports
      - positions
      title: ValveInfo
      description: "ports: an attribute representing the available ports on the stator\n\
        positions: an attribute mapping implicit, tacit numbers as keys to the stator\
        \ ports that are connected at this\n            position"
