# Nodes

devices:

    # Test device

    fakedevice1:
        FakeDevice:
            port: COM2

    # Analytics and sensors

    nmr:
        Spinsolve:
            host: BSMC-7WP43Y1
            port: 13000
            data_folder: W:\BS-FlowChemistry\Equipment\Magritek_NMR\data_exchange

    ir:
        FlowIR: {}

    p-sensor:
        PressureSensor:
            vint_serial_number: 627768

    # Temperature control

    heater:
        R4Heater:
            port: COM4

    chiller:
        HuberChiller:
            port: COM1

    # Pumps

    pump1:
        ML600:
            port: COM5
            address: 1
            syringe_volume: 5

    pump2:
        ML600:
            port: COM5
            address: 2
            syringe_volume: 5

    pump3:
        Elite11:
            port: COM6
            address: 1
            syringe_volume: 5
            diameter: 12.23

    # Other

    power-supply:
        MansonPowerSupply:
            port: COM7
