# Nodes
devices:
    fakedevice1:
        FakeDevice:
            port: COM2
    nmr:
        Spinsolve:
            host: BSMC-7WP43Y1
            port: 13000
            data_folder: W:\BS-FlowChemistry\Equipment\Magritek_NMR\data_exchange
    p1:
        PressureSensor:
            vint_serial_number: 627768
#    chiller:
#        HuberChiller:
#            port: COM1

#    pump1:
#        ML600:
#            port: COM5
#            address: 1
#            syringe_volume: 5
#
#    pump2:
#        ML600:
#            port: COM5
#            address: 2
#            syringe_volume: 5