# Nodes
fakedevice1:
    class: FakeDevice
    parameters:
        port: COM2
nmr:
    class: Spinsolve
    parameters:
        host: BSMC-7WP43Y1
        port: 13000
        data_folder: W:\BS-FlowChemistry\Equipment\Magritek_NMR\data_exchange
chiller:
    class: HuberChiller
    parameters:
        port: COM1
