openapi: 3.0.2
info:
  title: Flowchem - devices
  description: Flowchem is a python library to control a variety of instruments commonly
    found in chemistry labs.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 0.1.0a3
paths:
  /chiller-1/temperature:
    put:
      tags:
      - chiller-1
      - chiller-1
      summary: Set Temperature
      description: 'Set the target temperature to the given string in natural language.'
      operationId: chiller-1
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /chiller-1/power-on:
    put:
      tags:
      - chiller-1
      - chiller-1
      summary: Power On
      description: "Turn on temperature control."
      operationId: chiller-1
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /chiller-1/power-off:
    put:
      tags:
      - chiller-1
      - chiller-1
      summary: Power off
      description: "Turn off temperature control."
      operationId: chiller-1
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /chiller-1/target-reached:
    get:
      tags:
        - chiller-1
        - chiller-1
      summary: Has the temperature reached
      description: "Return True if the set temperature target has been reached."
      operationId: chiller-1
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
  /chiller-1/temperature/:
    get:
      tags:
        - chiller-1
        - chiller-1
      summary: Get Temperature
      description: "Return temperature in Celsius."
      operationId: chiller-1
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
