components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: Flowchem is a python library to control a variety of instruments commonly
    found in chemistry labs.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: Flowchem - devices
  version: 0.1.0a3
openapi: 3.0.2
paths:
  /hplc/exit:
    put:
      description: Exit Clarity Chrom.
      operationId: exit_hplc_exit_put
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Exit
      tags:
      - hplc
      - hplc
  /hplc/method:
    put:
      description: 'Sets the name of the sample for the next run.


        has to be done to open project, then method. Take care to select ''Send Method
        to Instrument'' option in Method

        Sending Options dialog in System Configuration.'
      operationId: set_method_hplc_method_put
      parameters:
      - in: query
        name: method_name
        required: true
        schema:
          title: Method Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Set Method
      tags:
      - hplc
      - hplc
  /hplc/run:
    put:
      description: 'Run one analysis on the instrument. Sample name has to be set
        in advance.


        Care should be taken to activate automatic data export on HPLC. (can be done
        via command,

        but that only makes it more complicated). Takes at least 2 sec until the run
        actually starts.'
      operationId: run_hplc_run_put
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Run
      tags:
      - hplc
      - hplc
  /hplc/sample-name:
    put:
      description: Sets the name of the sample for the next run.
      operationId: set_sample_name_hplc_sample_name_put
      parameters:
      - in: query
        name: sample_name
        required: true
        schema:
          title: Sample Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Set Sample Name
      tags:
      - hplc
      - hplc
