[device.socl2]
type = "Elite11InfuseWithdraw"
port = "COM4"
syringe_diameter = "14.567 mm"
syringe_volume = "10 ml"
baudrate = 115200

[device.hexyldecanoic]
type = "AzuraCompactPump"
ip_address = "192.168.1.119"
max_pressure = "10 bar"

[device.r4-heater]
type = "R4Heater"
port = "COM1"

[device.flowir]
type = "FlowIR"
url = "opc.tcp://localhost:62552/iCOpcUaServer"
