[device.socl2]
type = "Elite11InfuseWithdraw"
port = "COM4"
syringe_diameter = "4.6 mm"
syringe_volume = "1 ml"
baudrate = 115200

[device.hexyldecanoic]
type = "AzuraCompactPump"
ip_address = "192.168.1.119"
max_pressure = "10 bar"
