# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linting and testing + coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [
          "3.11",
          "3.12-dev",
        ]
        operating-system:
          - ubuntu-latest
          - windows-latest
#          - macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flowchem
        run: |
            python -m pip install .[dev,types,test]
            pip freeze

      - name: Run mypy
        run: |
            mypy --check-untyped-defs --python-version 3.11 --ignore-missing-imports ./src

      - name: Run ruff
        run: ruff .

      - name: Run pytest
        run: python -m pytest
