# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linting and testing + coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup nox

#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install flake8 pytest pytest-asyncio coverage[toml] mypy pytest-cov wheel
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#        pip install .
#
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=F401,F403,W503,E501
#
#    - name: Run mypy
#      run: |
#        mypy --install-types --non-interactive flowchem --python-version 3.9
#
#    - name: Test with pytest
#      run: |
#
#        coverage run -m pytest
#        coverage xml

      - name: Upload coverage data
        uses: "actions/upload-artifact@v2"
        with:
          name: coverage-data
          path: ".coverage.*"
          if-no-files-found: ignore

  coverage:
    runs-on: "ubuntu-latest"
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: "Install Coverage.py"
        run: "python -m pip install --upgrade coverage[toml]"

      - name: "Download coverage data"
        uses: actions/download-artifact@v2
        with:
          name: coverage-data

      - run: python -m coverage combine
      - run: python -m coverage html --skip-covered --skip-empty

      - name: Upload coverage report
        uses: "actions/upload-artifact@v2"
        with:
          name: html-report
          path: htmlcov

      - run: python -m coverage report --fail-under=100
